### ISSUE TITLE
Infinite recursion while processing year with `autofix: "pad"`

### ISSUE THREAD

**Issue by BadCoder1337** [uNmAnNeR/imaskjs#1054]
**Describe the bug**
Date mask throws an error when user tries to enter a 2-digit year into a 4-digit block.
```
Uncaught RangeError: Maximum call stack size exceeded
    at get displayValue (/node_modules/imask/dist/imask.js:2202:21)
    at MaskedRange._appendCharRaw (/node_modules/imask/dist/imask.js:2227:50)
    at MaskedRange._appendCharRaw (/node_modules/imask/dist/imask.js:2535:24)
    at MaskedRange._appendCharRaw (/node_modules/imask/dist/imask.js:2535:89)
    at MaskedRange._appendCharRaw (/node_modules/imask/dist/imask.js:2535:89)
    ......
```

**To Reproduce**
[CodeSandbox](https://codesandbox.io/p/sandbox/clever-easley-y24fky)
Enter `1.1.21` to the field.

**Expected behavior**
Input field shoud reject user input or pad with apropriate digit like `1111 -> 1951`

**Environment:**
 - `"imask": "7.6.1"`
 - `"react-imask": "7.6.1"`

**Comment by brunobely** [comment]
Not sure if related but getting the same error when entering a completely off value via autocomplete, like 12/3123211231_/yyyy on a Date mask (which I guess shouldn't even be allowed in the first place).

**Comment by sebmade** [comment]
same here, autofix: 'pad' has a bug with the yyyy 4 digit range mask
I fixed the issue by adding autofix: true on the yyyy blocks and keep autofix: 'pad' on the date mask config
`blocks: {
			dd: {
				mask: IMask.MaskedRange,
				from: 1,
				to: 31,
				maxLength: 2
			},
			mm: {
				mask: IMask.MaskedRange,
				from: 1,
				to: 12,
				maxLength: 2
			},
			yyyy: {
				mask: IMask.MaskedRange,
				from: 1930,
				to: new Date().getFullYear() - 6,
				maxLength: 4,
				autofix: true
			}
		},`
