### ISSUE TITLE
Problem using Angular Universal (Server Side Rendering)

### ISSUE THREAD

**Issue by LucasPaganini** [uNmAnNeR/imaskjs#115]
When building a regular Angular project, `angular-imask` works perfectly, but it does not work when running Angular on the server. This is probably a build problem since the generated `imask.directive.js` does not uses commonjs and the error explicit states `SyntaxError: Unexpected token import`.

### Error
```
/Users/lucas/Documents/dev/issue-reproduction/angular-imask-issue/node_modules/angular-imask/dist/imask.directive.js:13
import { Directive, ElementRef, Input, Output, forwardRef, Renderer2, EventEmitter, Optional, Inject } from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.angular-imask/dist/imask.directive (/Users/lucas/Documents/dev/issue-reproduction/angular-imask-issue/dist/server/main.js:575:18)
```

### Reproduction
The error can be reproduced adding `angular-imask` to the [Angular Universal starter kit](https://github.com/angular/universal-starter). 
I already did that in [this repository](https://github.com/LucasPaganini/angular-imask-issue), you can reproduce the error by running `npm install` and `npm run build:prerender && npm run build:ssr`.

**Comment by uNmAnNeR** [comment]
@LucasPaganini thanks for issue. `dist` files is generated by `ngc`. Probably only Angular knows how to use them all :) As I found `angular-imask.umd.js` file is commonjs build. I don't have time now to explore crazy Angular errors, which i collected a lot while doing Angular-plugin. May be community will help. Sorry about that, but even with reproduction steps (very thanks!) it will take too much time.

**Comment by uNmAnNeR** [comment]
@LucasPaganini i found same issue with another library
https://github.com/angular/universal-starter/issues/631
lets wait on it.

**Comment by SergeyKatugin** [comment]
what about fix?) we still need it fix, i don't wanna change you plugin

**Comment by LucasPaganini** [comment]
Hey man, what I did to "fix" it was to copy the plugin source code and just compile my project as usual, as if it was a code that I had written, that way it will be compiled correctly. Then I just import the IMaskModule in the modules that need it (you can import it once in the AppModule or in every lazy module that need it).

### Structure
```
imask/
  - imask.directive.ts
  - imask.module.ts
  - index.ts
```

### imask.directive.ts
```ts
import {
  Directive,
  ElementRef,
  Input,
  Output,
  forwardRef,
  Provider,
  Renderer2,
  EventEmitter,
  OnDestroy,
  OnChanges,
  AfterViewInit,
  Optional,
  Inject,
} from '@angular/core'
import { NG_VALUE_ACCESSOR, ControlValueAccessor, COMPOSITION_BUFFER_MODE } from '@angular/forms'
import { ɵgetDOM as getDOM } from '@angular/platform-browser'
import * as IMask from 'imask'

function _isAndroid(): boolean {
  const userAgent = getDOM() ? getDOM().getUserAgent() : ''
  return /android (\d+)/.test(userAgent.toLowerCase())
}

export const MASKEDINPUT_VALUE_ACCESSOR: Provider = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => IMaskDirective),
  multi: true,
}

const DEFAULT_IMASK_ELEMENT = elementRef => elementRef.nativeElement
@Directive({
  selector: '[imask]',
  host: {
    '(input)': '_handleInput($event.target.value)',
    '(blur)': 'onTouched()',
    '(compositionstart)': '_compositionStart()',
    '(compositionend)': '_compositionEnd($event.target.value)',
  },
  providers: [MASKEDINPUT_VALUE_ACCESSOR],
})
export class IMaskDirective implements ControlValueAccessor, AfterViewInit, OnDestroy, OnChanges {
  maskRef: any
  onTouched: any
  onChange: any
  private viewInitialized
  private _composing

  @Input()
  imask
  @Input()
  unmask?: boolean | 'typed'
  @Input()
  imaskElement: (elementRef: any, directiveRef: any) => any
  @Output()
  accept: EventEmitter<any>
  @Output()
  complete: EventEmitter<any>

  constructor(
    private _elementRef: ElementRef,
    private _renderer: Renderer2,
    @Optional()
    @Inject(COMPOSITION_BUFFER_MODE)
    private _compositionMode: boolean,
  ) {
    // init here to support AOT
    this.onTouched = () => {}
    this.onChange = () => {}
    this.imaskElement = DEFAULT_IMASK_ELEMENT
    this.accept = new EventEmitter()
    this.complete = new EventEmitter()
    this.viewInitialized = false
    this._composing = false

    if (this._compositionMode == null) {
      this._compositionMode = !_isAndroid()
    }
  }

  get element() {
    return this.imaskElement(this._elementRef, this)
  }

  get maskValue() {
    if (!this.maskRef) return this.element.value

    if (this.unmask === 'typed') return this.maskRef.typedValue
    if (this.unmask) return this.maskRef.unmaskedValue
    return this.maskRef.value
  }

  set maskValue(value) {
    if (this.maskRef) {
      if (this.unmask === 'typed') this.maskRef.typedValue = value
      else if (this.unmask) this.maskRef.unmaskedValue = value
      else this.maskRef.value = value
    } else {
      this._renderer.setProperty(this.element, 'value', value)
    }
  }

  ngAfterViewInit() {
    if (!this.imask) return

    this.initMask()
    this.viewInitialized = true
  }

  ngOnChanges(changes) {
    if (changes.elementRef && !this.imaskElement) this.imaskElement = DEFAULT_IMASK_ELEMENT

    if (!changes.imask || !this.viewInitialized) return

    if (this.imask) {
      if (this.maskRef) this.maskRef.updateOptions(this.imask)
      else {
        this.initMask()
        this.onChange(this.maskValue)
      }
    } else {
      this.destroyMask()
    }
  }

  destroyMask() {
    if (this.maskRef) {
      this.maskRef.destroy()
      delete this.maskRef
    }
  }

  ngOnDestroy() {
    this.destroyMask()
    this.accept.complete()
    this.complete.complete()
  }

  writeValue(value: any) {
    value = value == null ? '' : value

    if (this.maskRef) this.maskValue = value
    else this._renderer.setProperty(this.element, 'value', value)
  }

  _onAccept() {
    this.onChange(this.maskValue)
    this.onTouched()
    this.accept.emit(this.maskValue)
  }

  _onComplete() {
    this.complete.emit(this.maskValue)
  }

  private initMask() {
    this.maskRef = new IMask(this.element, this.imask)
      .on('accept', this._onAccept.bind(this))
      .on('complete', this._onComplete.bind(this))
  }

  setDisabledState(isDisabled: boolean) {
    this._renderer.setProperty(this.element, 'disabled', isDisabled)
  }

  registerOnChange(fn: (_: any) => void): void {
    this.onChange = fn
  }
  registerOnTouched(fn: () => void): void {
    this.onTouched = fn
  }

  _handleInput(value: any): void {
    // if mask is attached all input goes throw mask
    if (this.maskRef) return

    if (!this._compositionMode || (this._compositionMode && !this._composing)) {
      this.onChange(value)
    }
  }

  _compositionStart(): void {
    this._composing = true
  }

  _compositionEnd(value: any): void {
    this._composing = false
    this._compositionMode && this._handleInput(value)
  }
}
```

### imask.module.ts
```ts
import { NgModule } from '@angular/core'
import { CommonModule } from '@angular/common'

import { IMaskDirective } from './imask.directive'

@NgModule({
  imports: [CommonModule],
  declarations: [IMaskDirective],
  exports: [IMaskDirective],
})
export class IMaskModule {}
```

### index.ts
```ts
export * from './imask.directive'
export * from './imask.module'
```
