### ISSUE TITLE
Set the mask value when overwrite option is true throw an exception

### ISSUE THREAD

**Issue by AriasBros** [uNmAnNeR/imaskjs#171]
Currently, if we try set the value of the mask when we are using the overwrite option, we will get the next exception: `TypeError: checkTail.shiftBefore is not a function`

Example:

 ```
 describe('#update value when overwrite option is true', function () {
    it('should update mask and set new value', function () {
      imask.updateOptions({
        mask: Number,
        overwrite: true
      });

      const value = "100";
      imask.value = value;
      assert.strictEqual(imask.value, value);
    });
  });
```

Here is the code trace that we can get running the previous test:

> 1 failing
imask:   1) InputMask
imask:        #update value when overwrite is true
imask:          should update mask and set new value:
imask:      TypeError: checkTail.shiftBefore is not a function
imask:       at MaskedNumber.shiftBefore (src/masked/base.js:227:21)
imask:       at MaskedNumber._appendChar [as append] (src/masked/base.js:255:30)
imask:       at MaskedNumber.append [as resolve] (src/masked/base.js:122:10)
imask:       at MaskedNumber.resolve [as value] (src/masked/base.js:116:10)
imask:       at InputMask.set value [as value] (src/controls/input.js:96:5)
imask:       at Context.<anonymous> (test/controls/input.js: 100:7)

And, as we can see in the next screenshot, `checkTail` is an empty `String`.

![screenshot](https://user-images.githubusercontent.com/331765/57016912-e9dd7680-6c1c-11e9-91a7-b0cbe266d830.png)

**Comment by AriasBros** [comment]
Fixed in #172
