### ISSUE TITLE
Unit test failing for IMask with testing-library/react version 13.4.0

### ISSUE THREAD

**Issue by rajesh-situ** [uNmAnNeR/imaskjs#779]
**Describe the bug**
Getting the below error after upgrading the testing lib version 
TypeError: Cannot read property '_toggleEventHandler' of undefined

      62 |         // console.log('elm>>>>>>>>>>', IMask(elm, maskOptions));
      63 |         // eslint-disable-next-line
    > 64 |         maskedRef.current = IMask(elm, maskOptions)
         |                                  ^
      65 |         const masked = maskedRef.current
      66 |
      67 |         masked.on('accept', () => {

      at forEach (../../node_modules/imask/esm/controls/html-mask-element.js:105:23)
          at Array.forEach (<anonymous>)
      at HTMLMaskElement.bindEvents (../../node_modules/imask/esm/controls/html-mask-element.js:104:29)
      at InputMask._bindEvents (../../node_modules/imask/esm/controls/input.js:141:15)
      at new InputMask (../../node_modules/imask/esm/controls/input.js:56:10)

**To Reproduce**

**Expected behavior**
It should pass the test case with the latest react changes.

**Environment:**
 - IMask version: 6.4.3
 - Framework/plugin version if used - jest

**Additional context**

**Comment by uNmAnNeR** [comment]
please provide full example and feel free to reopen
